version: '3'

services:
    postgis:
        restart: always
        image: postgis/postgis:12-3.0-alpine
        environment:
            POSTGRES_PASSWORD: secret
        volumes:
            - postgis:/var/lib/postgresql/data
    adminer:
        image: adminer
        restart: always
        ports:
            - 5000:8080
        depends_on:
            - postgis
    geoserver:
        restart: on-failure
        image: guemidiborhane/geoserver:2.17.0
        build:
            context: .
            dockerfile: Dockerfile
            args:
                USER_ID: ${USER_ID}
                GROUP_ID: ${GROUP_ID}
                GS_VERSION: '2.17.0'
        volumes:
            - ./config:/opt/geoserver/data_dir
        ports:
            - '127.0.0.1:8000:8080'
        depends_on:
            - postgis

volumes:
    postgis:
